// Demo data for testing the UI without backend
export const demoBrands = [
  { id: 1, name: "Toyota", logo_url: "", description: "Quality and reliability leader" },
  { id: 2, name: "Honda", logo_url: "", description: "Innovation and efficiency" },
  { id: 3, name: "Ford", logo_url: "", description: "Built tough, built to last" },
  { id: 4, name: "BMW", logo_url: "", description: "The ultimate driving machine" },
  { id: 5, name: "Tesla", logo_url: "", description: "Accelerating sustainable transport" },
];

export const demoVehicles = [
  {
    id: 1,
    brand_id: 1,
    brand: { name: "Toyota" },
    name: "Camry",
    model: "LE",
    year: 2024,
    price: 28750,
    fuel_type: "Petrol",
    thumbnail_url: "https://via.placeholder.com/400x300/007bff/ffffff?text=Toyota+Camry",
    description: "Reliable midsize sedan with excellent fuel economy",
    engine_specs: "2.5L 4-Cylinder",
    transmission: "8-Speed Automatic",
    mileage: 32,
    exterior_color: "Midnight Black",
    interior_color: "Black Fabric",
    safety_features: "Toyota Safety Sense 2.0",
    financing_rate: 2.9,
    warranty_years: 3,
    dealer_info: "Downtown Toyota - (555) 123-4567",
    availability: true,
  },
  {
    id: 2,
    brand_id: 2,
    brand: { name: "Honda" },
    name: "Civic",
    model: "LX",
    year: 2024,
    price: 25200,
    fuel_type: "Petrol",
    thumbnail_url: "https://via.placeholder.com/400x300/28a745/ffffff?text=Honda+Civic",
    description: "Compact car with style and efficiency",
    engine_specs: "2.0L 4-Cylinder",
    transmission: "CVT",
    mileage: 35,
    exterior_color: "Sonic Gray",
    interior_color: "Black Cloth",
    safety_features: "Honda Sensing",
    financing_rate: 3.1,
    warranty_years: 3,
    dealer_info: "Metro Honda - (555) 234-5678",
    availability: true,
  },
  {
    id: 3,
    brand_id: 4,
    brand: { name: "BMW" },
    name: "3 Series",
    model: "330i",
    year: 2024,
    price: 45950,
    fuel_type: "Petrol",
    thumbnail_url: "https://via.placeholder.com/400x300/6c757d/ffffff?text=BMW+3+Series",
    description: "Ultimate sport sedan with luxury features",
    engine_specs: "2.0L TwinPower Turbo",
    transmission: "8-Speed Automatic",
    mileage: 28,
    exterior_color: "Alpine White",
    interior_color: "Black Sensatec",
    safety_features: "BMW Active Guard",
    financing_rate: 3.9,
    warranty_years: 4,
    dealer_info: "Luxury BMW - (555) 345-6789",
    availability: true,
  },
  {
    id: 4,
    brand_id: 5,
    brand: { name: "Tesla" },
    name: "Model 3",
    model: "Long Range",
    year: 2024,
    price: 47740,
    fuel_type: "Electric",
    thumbnail_url: "https://via.placeholder.com/400x300/dc3545/ffffff?text=Tesla+Model+3",
    description: "Premium electric sedan with autopilot",
    engine_specs: "Dual Motor AWD",
    transmission: "Single-Speed",
    mileage: 358,
    exterior_color: "Pearl White",
    interior_color: "Black Premium",
    safety_features: "Autopilot Included",
    financing_rate: 2.99,
    warranty_years: 4,
    dealer_info: "Tesla Service Center - (555) 456-7890",
    availability: true,
  },
  {
    id: 5,
    brand_id: 3,
    brand: { name: "Ford" },
    name: "F-150",
    model: "XLT",
    year: 2024,
    price: 42970,
    fuel_type: "Petrol",
    thumbnail_url: "https://via.placeholder.com/400x300/ffc107/000000?text=Ford+F-150",
    description: "America's best-selling truck",
    engine_specs: "3.3L V6",
    transmission: "10-Speed Automatic",
    mileage: 24,
    exterior_color: "Oxford White",
    interior_color: "Medium Earth Gray",
    safety_features: "Ford Co-Pilot360",
    financing_rate: 3.5,
    warranty_years: 3,
    dealer_info: "Ford Country - (555) 567-8901",
    availability: true,
  },
  {
    id: 6,
    brand_id: 1,
    brand: { name: "Toyota" },
    name: "Prius",
    model: "LE",
    year: 2024,
    price: 27450,
    fuel_type: "Hybrid",
    thumbnail_url: "https://via.placeholder.com/400x300/17a2b8/ffffff?text=Toyota+Prius",
    description: "Most fuel-efficient hybrid sedan",
    engine_specs: "1.8L Hybrid",
    transmission: "CVT",
    mileage: 58,
    exterior_color: "Blue Crush",
    interior_color: "Black SofTex",
    safety_features: "Toyota Safety Sense 2.0",
    financing_rate: 2.4,
    warranty_years: 3,
    dealer_info: "Downtown Toyota - (555) 123-4567",
    availability: true,
  },
];

export const demoAnalytics = {
  total_vehicles: 6,
  vehicles_by_brand: {
    "Toyota": 2,
    "Honda": 1,
    "BMW": 1,
    "Tesla": 1,
    "Ford": 1,
  },
  vehicles_by_fuel: {
    "Petrol": 4,
    "Electric": 1,
    "Hybrid": 1,
  },
  total_bookings: 12,
  bookings_by_status: {
    "pending": 8,
    "contacted": 3,
    "completed": 1,
  },
  average_price: 36343.33,
  price_range: {
    "min": 25200,
    "max": 47740,
  },
};